- sample/android-app/src/main/res/values/styles.xml
- sample/mpp-library/src/commonMain/kotlin/App.kt
- sample/mpp-library/src/commonMain/kotlin/com/icerockdev/library/AppTheme.kt
- sample/mpp-library/src/commonMain/kotlin/com/icerockdev/library/universal/LoginScreen.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/factory/SystemInputViewFactory.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/style/ext/LayoutParamsExt.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/utils/DpExt.kt
> #10 input underline bug android

- sample/mpp-library/src/commonMain/kotlin/com/icerockdev/library/AppTheme.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/factory/SystemInputViewFactory.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/factory/SystemInputViewFactory.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/utils/TextStyleExt.kt
> #12 input textstyle bug

- sample/mpp-library/src/commonMain/kotlin/com/icerockdev/library/AppTheme.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/factory/SystemButtonViewFactory.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/style/background/BackgroundExt.kt
- widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/factory/SystemButtonViewFactory.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/factory/SystemButtonViewFactory.kt
fix #14 - added abitily to control elevation of android buttons
> #14 transparent button elevation

- sample/mpp-library/src/commonMain/kotlin/com/icerockdev/library/AppTheme.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/factory/SystemInputViewFactory.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/style/ext/TextAlignmentExt.kt
Fixes for sample-app was implemented. 
And adds some explaining comments.
> #40: fix sample-app for new text alignments enums and add some comments

- README.md
- buildSrc/src/main/kotlin/Versions.kt
> Release 0.1.0 dev 9

- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/navigation/BottomNavigationScreen.kt
- widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/screen/navigation/BottomNavigationScreen.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/screen/navigation/BottomNavigationScreen.kt
Add navBar colors, title mod labeled/unlabeled
> #48 add navBar colors

- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/factory/CheckboxSwitchViewFactory.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/factory/ConstraintViewFactory.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/factory/FloatingLabelInputViewFactory.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/factory/SystemCollectionViewFactory.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/factory/SystemInputViewFactory.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/factory/SystemListViewFactory.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/factory/SystemScrollViewFactory.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/factory/SystemSingleChoiceViewFactory.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/factory/SystemSwitchViewFactory.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/utils/IdExt.kt
fix of #61 but without correct android save instance state work (state will not restore)
> temporary fix of #61

- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/factory/WebViewFactory.kt
- widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/WebViewWidget.kt
- widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/factory/WebViewFactory.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/factory/WebViewFactory.kt
#55: WebViewWidget implementation for Android and iOS.
> Simple WebViewWidget implementation [android, ios]

- sample/mpp-library/src/commonMain/kotlin/App.kt
- sample/mpp-library/src/commonMain/kotlin/com/icerockdev/library/universal/InfoWebViewScreen.kt
- sample/mpp-library/src/commonMain/kotlin/com/icerockdev/library/universal/LoginScreen.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/factory/WebViewFactory.kt
- widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/WebViewWidget.kt
- widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/utils/WebViewRedirectUrlHandler.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/factory/WebViewFactory.kt
#66 [Android, iOS]: WebViewWidget redirects handling implementation.
> #66: Success and failure redirects handlers for WebViewWidget

- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/factory/FloatingLabelInputViewFactory.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/factory/SystemInputViewFactory.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/style/InputTypes.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/utils/DefaultTextFormatter.kt
Added iOS implementation for input type for Floating Label Input Widget
> Ios input type impl

- sample/mpp-library/src/commonMain/kotlin/App.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/navigation/BottomNavigationScreen.kt
- widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/screen/navigation/BottomNavigationScreen.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/screen/navigation/BottomNavigationScreen.kt
fix #48 API issue
implement #26 icons customization
> #26 buttom navigation icon

- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/ShowAlertExt.kt
- widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/screen/ShowAlertExt.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/screen/ShowAlertExt.kt
added showing dialog from screens
> #4 show dialog

- sample/android-app/src/main/java/com/icerockdev/MainApplication.kt
- sample/ios-app/src/AppDelegate.swift
- sample/mpp-library/src/commonMain/kotlin/App.kt
- sample/mpp-library/src/commonMain/kotlin/com/icerockdev/library/universal/LoginScreen.kt
- widgets/build.gradle.kts
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/HostActivity.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/Screen.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/ShowAlertExt.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/navigation/RouteHandler.kt
- widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/screen/BaseApplication.kt
- widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/screen/ShowAlertExt.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/screen/Screen.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/screen/ShowAlertExt.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/screen/navigation/RouteHandler.kt
> show alert dialog from screen API

- sample/mpp-library/src/commonMain/kotlin/com/icerockdev/library/universal/LoginScreen.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/HostActivity.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/navigation/BottomNavigationScreen.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/navigation/NavigationScreen.kt
> android back button fix

- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/navigation/NavigationScreen.kt
- widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/screen/navigation/NavigationScreen.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/screen/navigation/NavigationScreen.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/style/NavigationBarExt.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/utils/NavigationItemActionExt.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/utils/TextStyleExt.kt
Added iOS implementation for Navigation bar customization
> #9 System Navbar customization

- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/factory/SystemImageViewFactory.kt
- widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/factory/SystemImageViewFactory.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/factory/SystemImageViewFactory.kt
corner radius for iOS implemented. Android required
> #78 image view factory

- buildSrc/src/main/kotlin/Deps.kt
- buildSrc/src/main/kotlin/Versions.kt
- sample/mpp-library/src/commonMain/kotlin/App.kt
- sample/mpp-library/src/commonMain/kotlin/com/icerockdev/library/universal/LoginScreen.kt
- widgets/build.gradle.kts
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/factory/SystemImageViewFactory.kt
- widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/factory/SystemImageViewFactory.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/factory/SystemImageViewFactory.kt
> image rounded corners

- sample/mpp-library/src/commonMain/kotlin/com/icerockdev/library/universal/CartScreen.kt
- sample/mpp-library/src/commonMain/kotlin/com/icerockdev/library/universal/LoginScreen.kt
- sample/mpp-library/src/commonMain/kotlin/com/icerockdev/library/universal/ProductScreen.kt
- sample/mpp-library/src/commonMain/kotlin/com/icerockdev/library/universal/ProductsScreen.kt
- sample/mpp-library/src/commonMain/kotlin/com/icerockdev/library/universal/ProfileScreen.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/navigation/BottomNavigationScreen.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/navigation/NavigationScreen.kt
- widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/screen/navigation/Route.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/screen/navigation/BottomNavigationScreen.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/screen/navigation/NavigationScreen.kt
#83 remove source screen argument from simple Route interface (unused at all)
> Route interface simplify

- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/navigation/NavigationScreen.kt
fix #94 
disable statusbar color setup to fix adjust view size
> #94 fix keyboard adjust on android

- sample/mpp-library/src/commonMain/kotlin/com/icerockdev/library/sample/CryptoProfileSample.kt
- sample/mpp-library/src/commonMain/kotlin/com/icerockdev/library/sample/McommerceProfileSample.kt
- sample/mpp-library/src/commonMain/kotlin/com/icerockdev/library/sample/SocialProfileSample.kt
- sample/mpp-library/src/commonMain/kotlin/com/icerockdev/library/universal/LoginScreen.kt
- widgets-flat/src/iosMain/kotlin/dev/icerock/moko/widgets/flat/FlatInputViewFactory.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/style/InputTypes.kt
- widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/style/input/InputType.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/factory/FloatingLabelInputViewFactory.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/factory/SystemInputViewFactory.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/style/InputTypes.kt
Type changed, sample updated.
!!!! Required change current types usage from `InputType.PHONE` to `InputType.Phone()` !!!!
> #99 InputType implementation changed with sealed class

- sample/ios-app/src/AppDelegate.swift
- sample/ios-app/src/Info.plist
- sample/mpp-library/src/commonMain/kotlin/App.kt
- sample/mpp-library/src/commonMain/kotlin/dev/icerock/moko/widgets/sample/SelectGalleryScreen.kt
- sample/mpp-library/src/iosMain/kotlin/com/icerockdev/library/universal/PlatformProfileScreen.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/HostActivity.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/Screen.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/navigation/NavigationScreen.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/utils/ThemeAttrs.kt
- widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/screen/BaseApplication.kt
- widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/screen/Screen.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/screen/ApplicationHolder.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/screen/Screen.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/screen/WidgetScreen.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/screen/WidgetViewController.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/screen/navigation/BottomNavigationScreen.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/screen/navigation/NavigationScreen.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/utils/StatusBarExt.kt
fix #102 
added control of android statusBarColor
added control of status bar content style (light/dark)
> StatusBar color API

- widgets-bottomsheet/src/androidMain/kotlin/dev/icerock/moko/widgets/bottomsheet/BottomSheet.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/ShowAlertExt.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/ToastAlertsExt.kt
> fix illegal state exception on android

- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/factory/SystemTextViewFactory.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/utils/UIViewExt.kt
for text widget it needs special realization because UIlabel is subview of ViewBundle
> #117 added compression resistance for views with wrapContent 

- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/factory/ClickableViewFactory.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/factory/SystemTabsViewFactory.kt
> ripple on clickable

- sample/mpp-library/src/commonMain/kotlin/App.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/navigation/NavigationScreen.kt
- widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/screen/navigation/NavigationScreen.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/screen/navigation/NavigationScreen.kt
> route to initial in NavigationScrren

- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/screen/WidgetViewController.kt
Fixed touches handling for UIControl items
> #108 tap keyboard dismiss

- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/HideKeyboardExt.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/WidgetScreen.kt
> invalid ripple on root

- sample/mpp-library/src/commonMain/kotlin/App.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/FragmentNavigation.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/navigation/BottomNavigationScreen.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/navigation/NavigationScreen.kt
> Android lost backstack view state

- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/navigation/NavigationScreen.kt
Add children fragments to targets for result
> #128 android result route navigation

- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/DatePickerDialogHandler.kt
- widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/screen/ShowDatePickerExt.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/screen/ShowDatePickerExt.kt
need to implement selected date for android
> #90 added date picker for ios

- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/DatePickerDialogHandler.kt
Add SelectedDate to android datapicker
> #90 SelectedDate on Android DatePicker

- sample/mpp-library/src/commonMain/kotlin/App.kt
- sample/mpp-library/src/commonMain/kotlin/dev/icerock/moko/widgets/sample/TabsSampleScreen.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/style/NavigationBarNormal.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/style/NavigationBarSearch.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/style/NavigationBarStyles.kt
- widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/screen/navigation/NavigationScreen.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/style/NavigationBarExt.kt
add ability to remove shadow of navigationbar to implement extended like navbar
> tabs in navigation bar fix

- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/factory/SystemImageViewFactory.kt
if height is WrapContent:
without adjustViewBounds, ImageView set height like in image
with adjustViewBounds ImageView save aspect ratio of Image
> #162 Add adjustViewBounds to SystemImageViewFactory

- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/factory/SystemTextViewFactory.kt
- widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/TextWidget.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/factory/SystemTextViewFactory.kt
add maxLines: LiveData<Int?>? to TextWidget, add bind into SystemTextViewFactory
> #161 Add maxLines to TextWidget

- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/factory/ButtonWithIconViewFactory.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/factory/ButtonWithIconViewFactory.kt
> #95: unwanted icon tint of ButtonWithIconViewFactory was removed

- widgets-bottomsheet/src/androidMain/kotlin/dev/icerock/moko/widgets/bottomsheet/BottomSheet.kt
- widgets-bottomsheet/src/commonMain/kotlin/dev/icerock/moko/widgets/bottomsheet/BottomSheet.kt
- widgets-bottomsheet/src/iosMain/kotlin/dev/icerock/moko/widgets/bottomSheet/BottomSheet.kt
- widgets-bottomsheet/src/iosMain/swift/BottomSheetController.swift
by the way fix:
- corners at top of bottom sheet
- dismissing bottom sheet by scroll down
> #158 dismiss bottom sheet

- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/screen/Screen.kt
- widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/screen/Screen.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/screen/Screen.kt
need confirmation, is it ok for android
> #178 added open func onViewCreated

- .github/workflows/compilation-check.yml
- .github/workflows/publish.yml
- README.md
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/Deps.kt
- buildSrc/src/main/kotlin/Versions.kt
- gradle/wrapper/gradle-wrapper.properties
- publishToMavenLocal.sh
- settings.gradle.kts
- widgets-collection/src/iosMain/kotlin/dev/icerock/moko/widgets/collection/SimpleCollectionViewFactory.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/factory/SystemListViewFactory.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/screen/ToastAlertsExt.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/units/UnitItemExt.kt
- kotlin 1.3.70
- android gradle plugin 3.6.1
- gradle 5.6.4
- klock 1.9.1
- coroutines 1.3.4
- fix iOS 12 crash #187 
- fix iOS toast overlay #186
> Release 0.1.0-dev-16

- README.md
- buildSrc/src/main/kotlin/Versions.kt
- widgets-collection/src/iosMain/kotlin/dev/icerock/moko/widgets/collection/SimpleCollectionViewFactory.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/factory/SystemListViewFactory.kt
Hotfix of ios framework compilation error. 
moko-units updated to 0.3.1
> Release 0.1.0-dev-17

- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/factory/WebViewFactory.kt
- widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/WebViewWidget.kt
> #192 pass domStorageEnabled param

- README.md
- buildSrc/src/main/kotlin/Versions.kt
- widgets-datetime-picker/src/iosMain/kotlin/dev/icerock/moko/widgets/datetimepicker/ShowDatePickerExt.kt
> Release 0.1.0-dev-19

- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/factory/SystemInputViewFactory.kt
Process field value formatting
> Input formatter fix on iOS

- .github/workflows/compilation-check.yml
- .github/workflows/publish-dev.yml
- .github/workflows/publish.yml
- buildSrc/src/main/kotlin/Deps.kt
- buildSrc/src/main/kotlin/Versions.kt
- publishToMavenLocal.sh
- sample/android-app/src/main/AndroidManifest.xml
- sample/mpp-library/build.gradle.kts
- sample/mpp-library/src/commonMain/kotlin/App.kt
- sample/mpp-library/src/commonMain/kotlin/dev/icerock/moko/widgets/sample/MediaScreen.kt
- sample/mpp-library/src/commonMain/kotlin/dev/icerock/moko/widgets/sample/PermissionsScreen.kt
- settings.gradle.kts
- widgets-media/build.gradle.kts
- widgets-media/src/androidMain/AndroidManifest.xml
- widgets-media/src/androidMain/kotlin/dev/icerock/moko/widgets/media/ImageBitmap.kt
- widgets-media/src/androidMain/kotlin/dev/icerock/moko/widgets/media/MediaControllerExt.kt
- widgets-media/src/commonMain/kotlin/dev/icerock/moko/widgets/media/ImageBitmap.kt
- widgets-media/src/commonMain/kotlin/dev/icerock/moko/widgets/media/MediaControllerExt.kt
- widgets-media/src/iosArm64Main
- widgets-media/src/iosMain/kotlin/dev/icerock/moko/widgets/media/ImageBitmap.kt
- widgets-media/src/iosMain/kotlin/dev/icerock/moko/widgets/media/MediaControllerExt.kt
- widgets-media/src/iosX64Main
- widgets-permissions/src/androidMain/kotlin/dev/icerock/moko/widgets/permissions/PermissionsControllerExt.kt
- widgets-permissions/src/commonMain/kotlin/dev/icerock/moko/widgets/permissions/PermissionsControllerExt.kt
- widgets-permissions/src/iosMain/kotlin/dev/icerock/moko/widgets/permissions/PermissionsControllerExt.kt
- widgets/build.gradle.kts
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/core/Image.kt
- widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/core/Image.kt
- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/core/Image.kt
- MediaPickerController extensions for Screen
- Image.bitmap moved from core to widgets-media
> moko-media additions

- kotlin-common-plugin/src/main/kotlin/dev/icerock/moko/widgets/CommonGenerator.kt
- widgets/src/androidMain/kotlin/dev/icerock/moko/widgets/core/utils/IdExt.kt
- widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/core/StringId.kt
runtime ids can be created with autogenerated functions like:
`inputWidgetId(uniqueId = "myUniqueId")`
`buttonWidgetId(uniqueId = "myUniqueId")`
> #199 add ability to create id in runtime

- widgets-sms/src/androidMain/kotlin/dev/icerock/moko/widgets/sms/SmsInputViewFactory.kt
> #226 SmsInputViewFactory fix

- kotlin-common-plugin/src/main/kotlin/dev/icerock/moko/widgets/CommonGenerator.kt
- widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/core/widget/FlatAlertWidget.kt
#241: Add widget factory argument to common generator and add custom widget factories arguments to flat-alert.
> #241: Add custom widget factories to flat-alert

- .github/workflows/publish-dev.yml
- .github/workflows/publish.yml
- build.gradle.kts
Disable maven-publish plugin's validation of publishing - it increase stability of publish action with bintray
> Publish fix

- .github/workflows/compilation-check.yml
- .github/workflows/publish-dev.yml
- .github/workflows/publish.yml
- build.gradle.kts
- buildSrc/src/main/kotlin/dev/icerock/moko/widgets/gradle/BintrayPublishingPlugin.kt
- buildSrc/src/main/kotlin/dev/icerock/moko/widgets/gradle/PublishToBintrayRepository.kt
- buildSrc/src/main/kotlin/org/gradle/api/publish/maven/internal/publisher/BintrayPublisher.kt
- gradle-plugin/build.gradle.kts
- kotlin-native-plugin/build.gradle.kts
- kotlin-plugin/build.gradle.kts
- publishToMavenLocal.sh
new publishing tasks and custom artifact publisher without bintray's illegal filetypes
> bintray publishing fix

- widgets/src/iosMain/kotlin/dev/icerock/moko/widgets/core/factory/SystemTextViewFactory.kt
> #266: add word line break mode for SystemTextViewFactory

- README.md
- gradle/libs.versions.toml
- widgets-datetime-picker/src/iosMain/kotlin/dev/icerock/moko/widgets/datetimepicker/ShowDatePickerExt.kt
> Release 0.2.1
